### ISSUE TITLE
Cancel please , figured out issue

### ISSUE THREAD

**Issue by Ecredx** [LeonBlade/DalamudPlugins#5]
Cancel please

**Comment by Ecredx** [comment]
Hi, sorry to bother you again,

I was able to open the housing menu with bdth list and I don't know if I am
remembering incorrectly, but the list used to come up automatically when
opening the housing menu as opposed to typing it out. Is this still
possible ?

**Comment by LeonBlade** [comment]
What do you mean by typing it out?

**Comment by Ecredx** [comment]
For instance, if you type out /bdth list, the plugin will show all the
items in the house. Before 6.0,I remember the plugin doing this
automatically. Is there an option to enable this ? Thank you again !

**Comment by LeonBlade** [comment]
Ah, the list is currently disabled due to a reported issue where it crashes the game. Since the game is currently suffering from long queue times to get into the servers, I have disabled this to prevent people from crashing until I have the time to research the bug more closely and solve it.

**Comment by Ecredx** [comment]
Thank you for explaining,

Really appreciate your work on the plugin!
