### ISSUE TITLE
Y Coordinate won't save 

### ISSUE THREAD

**Issue by loveemetoinfinitybabe** [LeonBlade/DalamudPlugins#6]
I'm not sure if it's related to your plug in or if it's the game itself, but whenever I try to move on object on the Y axis to raise or lower it, it doesn't actually save the location and just snaps back to the vanilla location when you exit the housing menu. Before I had no issue and now my location for the fireplace is low instead of higher where I placed it before the update. Just wanted to let you know.

**Comment by LeonBlade** [comment]
This isn't a bug, this is just how the game works. You can look at the Discord channel to see the spreadsheet in the pins. It's a limitation to the game, and objects have to move a minimum distance from the floor for their position to change.

**Comment by loveemetoinfinitybabe** [comment]
hmm thats weird then because the items are being moved more than their minmums and still snap back to the original positions. I'll keep messing around with it and see if it finally sticks in a different way. Thanks for the reply!
